# Generated by Django 4.2 on 2025-08-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
