# Generated by Django 4.2 on 2025-08-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
